"""cursos

Revision ID: 79a419a3b9cd
Revises: a6200f4e68c8
Create Date: 2023-11-15 17:12:37.137518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a419a3b9cd'
down_revision = 'a6200f4e68c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=5), nullable=True),
    sa.Column('especialidad', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('lunes', sa.String(length=20), nullable=True),
    sa.Column('martes', sa.String(length=20), nullable=True),
    sa.Column('miercoles', sa.String(length=20), nullable=True),
    sa.Column('jueves', sa.String(length=20), nullable=True),
    sa.Column('viernes', sa.String(length=20), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso')
    # ### end Alembic commands ###
